/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.records;


import cfm.onthi.entities.tables.OtCourse;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_course",
    schema = "s_onthi",
    indexes = {
        @Index(name = "ID_TEACHER", columnList = "ID_TEACHER ASC")
    }
)
public class OtCourseRecord extends UpdatableRecordImpl<OtCourseRecord> implements Record15<Long, Long, String, String, String, String, Long, LocalDate, LocalDate, Double, Double, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>s_onthi.ot_course.ID_COURSE</code>.
     */
    public void setIdCourse(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.ID_COURSE</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_COURSE", nullable = false)
    public Long getIdCourse() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>s_onthi.ot_course.ID_TEACHER</code>.
     */
    public void setIdTeacher(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.ID_TEACHER</code>.
     */
    @Column(name = "ID_TEACHER", nullable = false)
    public Long getIdTeacher() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>s_onthi.ot_course.AVATAR_COURSE</code>.
     */
    public void setAvatarCourse(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.AVATAR_COURSE</code>.
     */
    @Column(name = "AVATAR_COURSE", length = 5000)
    public String getAvatarCourse() {
        return (String) get(2);
    }

    /**
     * Setter for <code>s_onthi.ot_course.CATEGORY_NAME</code>.
     */
    public void setCategoryName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.CATEGORY_NAME</code>.
     */
    @Column(name = "CATEGORY_NAME", length = 100)
    public String getCategoryName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>s_onthi.ot_course.SCHEDULE</code>.
     */
    public void setSchedule(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.SCHEDULE</code>.
     */
    @Column(name = "SCHEDULE", length = 500)
    public String getSchedule() {
        return (String) get(4);
    }

    /**
     * Setter for <code>s_onthi.ot_course.COURSE_NAME</code>.
     */
    public void setCourseName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.COURSE_NAME</code>.
     */
    @Column(name = "COURSE_NAME", nullable = false, length = 100)
    public String getCourseName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>s_onthi.ot_course.TYPE_COURSE</code>.
     */
    public void setTypeCourse(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.TYPE_COURSE</code>.
     */
    @Column(name = "TYPE_COURSE")
    public Long getTypeCourse() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>s_onthi.ot_course.START_DATE</code>.
     */
    public void setStartDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.START_DATE</code>.
     */
    @Column(name = "START_DATE")
    public LocalDate getStartDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>s_onthi.ot_course.END_DATE</code>.
     */
    public void setEndDate(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.END_DATE</code>.
     */
    @Column(name = "END_DATE")
    public LocalDate getEndDate() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>s_onthi.ot_course.PRICE</code>.
     */
    public void setPrice(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.PRICE</code>.
     */
    @Column(name = "PRICE", nullable = false)
    public Double getPrice() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>s_onthi.ot_course.DISCOUNT</code>.
     */
    public void setDiscount(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.DISCOUNT</code>.
     */
    @Column(name = "DISCOUNT")
    public Double getDiscount() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>s_onthi.ot_course.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.DESCRIPTION</code>.
     */
    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return (String) get(11);
    }

    /**
     * Setter for <code>s_onthi.ot_course.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>s_onthi.ot_course.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>s_onthi.ot_course.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>s_onthi.ot_course.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, Long, String, String, String, String, Long, LocalDate, LocalDate, Double, Double, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, Long, String, String, String, String, Long, LocalDate, LocalDate, Double, Double, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OtCourse.OT_COURSE.ID_COURSE;
    }

    @Override
    public Field<Long> field2() {
        return OtCourse.OT_COURSE.ID_TEACHER;
    }

    @Override
    public Field<String> field3() {
        return OtCourse.OT_COURSE.AVATAR_COURSE;
    }

    @Override
    public Field<String> field4() {
        return OtCourse.OT_COURSE.CATEGORY_NAME;
    }

    @Override
    public Field<String> field5() {
        return OtCourse.OT_COURSE.SCHEDULE;
    }

    @Override
    public Field<String> field6() {
        return OtCourse.OT_COURSE.COURSE_NAME;
    }

    @Override
    public Field<Long> field7() {
        return OtCourse.OT_COURSE.TYPE_COURSE;
    }

    @Override
    public Field<LocalDate> field8() {
        return OtCourse.OT_COURSE.START_DATE;
    }

    @Override
    public Field<LocalDate> field9() {
        return OtCourse.OT_COURSE.END_DATE;
    }

    @Override
    public Field<Double> field10() {
        return OtCourse.OT_COURSE.PRICE;
    }

    @Override
    public Field<Double> field11() {
        return OtCourse.OT_COURSE.DISCOUNT;
    }

    @Override
    public Field<String> field12() {
        return OtCourse.OT_COURSE.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return OtCourse.OT_COURSE.CREATED_DATE;
    }

    @Override
    public Field<String> field14() {
        return OtCourse.OT_COURSE.LAST_MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return OtCourse.OT_COURSE.LAST_MODIFIED_DATE;
    }

    @Override
    public Long component1() {
        return getIdCourse();
    }

    @Override
    public Long component2() {
        return getIdTeacher();
    }

    @Override
    public String component3() {
        return getAvatarCourse();
    }

    @Override
    public String component4() {
        return getCategoryName();
    }

    @Override
    public String component5() {
        return getSchedule();
    }

    @Override
    public String component6() {
        return getCourseName();
    }

    @Override
    public Long component7() {
        return getTypeCourse();
    }

    @Override
    public LocalDate component8() {
        return getStartDate();
    }

    @Override
    public LocalDate component9() {
        return getEndDate();
    }

    @Override
    public Double component10() {
        return getPrice();
    }

    @Override
    public Double component11() {
        return getDiscount();
    }

    @Override
    public String component12() {
        return getDescription();
    }

    @Override
    public LocalDateTime component13() {
        return getCreatedDate();
    }

    @Override
    public String component14() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime component15() {
        return getLastModifiedDate();
    }

    @Override
    public Long value1() {
        return getIdCourse();
    }

    @Override
    public Long value2() {
        return getIdTeacher();
    }

    @Override
    public String value3() {
        return getAvatarCourse();
    }

    @Override
    public String value4() {
        return getCategoryName();
    }

    @Override
    public String value5() {
        return getSchedule();
    }

    @Override
    public String value6() {
        return getCourseName();
    }

    @Override
    public Long value7() {
        return getTypeCourse();
    }

    @Override
    public LocalDate value8() {
        return getStartDate();
    }

    @Override
    public LocalDate value9() {
        return getEndDate();
    }

    @Override
    public Double value10() {
        return getPrice();
    }

    @Override
    public Double value11() {
        return getDiscount();
    }

    @Override
    public String value12() {
        return getDescription();
    }

    @Override
    public LocalDateTime value13() {
        return getCreatedDate();
    }

    @Override
    public String value14() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime value15() {
        return getLastModifiedDate();
    }

    @Override
    public OtCourseRecord value1(Long value) {
        setIdCourse(value);
        return this;
    }

    @Override
    public OtCourseRecord value2(Long value) {
        setIdTeacher(value);
        return this;
    }

    @Override
    public OtCourseRecord value3(String value) {
        setAvatarCourse(value);
        return this;
    }

    @Override
    public OtCourseRecord value4(String value) {
        setCategoryName(value);
        return this;
    }

    @Override
    public OtCourseRecord value5(String value) {
        setSchedule(value);
        return this;
    }

    @Override
    public OtCourseRecord value6(String value) {
        setCourseName(value);
        return this;
    }

    @Override
    public OtCourseRecord value7(Long value) {
        setTypeCourse(value);
        return this;
    }

    @Override
    public OtCourseRecord value8(LocalDate value) {
        setStartDate(value);
        return this;
    }

    @Override
    public OtCourseRecord value9(LocalDate value) {
        setEndDate(value);
        return this;
    }

    @Override
    public OtCourseRecord value10(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public OtCourseRecord value11(Double value) {
        setDiscount(value);
        return this;
    }

    @Override
    public OtCourseRecord value12(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public OtCourseRecord value13(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public OtCourseRecord value14(String value) {
        setLastModifiedBy(value);
        return this;
    }

    @Override
    public OtCourseRecord value15(LocalDateTime value) {
        setLastModifiedDate(value);
        return this;
    }

    @Override
    public OtCourseRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, Long value7, LocalDate value8, LocalDate value9, Double value10, Double value11, String value12, LocalDateTime value13, String value14, LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OtCourseRecord
     */
    public OtCourseRecord() {
        super(OtCourse.OT_COURSE);
    }

    /**
     * Create a detached, initialised OtCourseRecord
     */
    public OtCourseRecord(Long idCourse, Long idTeacher, String avatarCourse, String categoryName, String schedule, String courseName, Long typeCourse, LocalDate startDate, LocalDate endDate, Double price, Double discount, String description, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate) {
        super(OtCourse.OT_COURSE);

        setIdCourse(idCourse);
        setIdTeacher(idTeacher);
        setAvatarCourse(avatarCourse);
        setCategoryName(categoryName);
        setSchedule(schedule);
        setCourseName(courseName);
        setTypeCourse(typeCourse);
        setStartDate(startDate);
        setEndDate(endDate);
        setPrice(price);
        setDiscount(discount);
        setDescription(description);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
    }

    /**
     * Create a detached, initialised OtCourseRecord
     */
    public OtCourseRecord(cfm.onthi.entities.tables.pojos.OtCourse value) {
        super(OtCourse.OT_COURSE);

        if (value != null) {
            setIdCourse(value.getIdCourse());
            setIdTeacher(value.getIdTeacher());
            setAvatarCourse(value.getAvatarCourse());
            setCategoryName(value.getCategoryName());
            setSchedule(value.getSchedule());
            setCourseName(value.getCourseName());
            setTypeCourse(value.getTypeCourse());
            setStartDate(value.getStartDate());
            setEndDate(value.getEndDate());
            setPrice(value.getPrice());
            setDiscount(value.getDiscount());
            setDescription(value.getDescription());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
        }
    }
}
