/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.records;


import cfm.onthi.entities.tables.OtQuiz;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_quiz",
    schema = "s_onthi"
)
public class OtQuizRecord extends UpdatableRecordImpl<OtQuizRecord> implements Record12<Long, Long, String, String, Long, String, String, Long, Integer, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    public void setIdQuiz(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_QUIZ", nullable = false)
    public Long getIdQuiz() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_EXERCISE</code>.
     */
    public void setIdExercise(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_EXERCISE</code>.
     */
    @Column(name = "ID_EXERCISE", nullable = false)
    public Long getIdExercise() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    public void setContentQuiz(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    @Column(name = "CONTENT_QUIZ", nullable = false)
    public String getContentQuiz() {
        return (String) get(2);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.OPTIONS</code>.
     */
    public void setOptions(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.OPTIONS</code>.
     */
    @Column(name = "OPTIONS")
    public String getOptions() {
        return (String) get(3);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.QUIZ_TYPE</code>.
     */
    public void setQuizType(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.QUIZ_TYPE</code>.
     */
    @Column(name = "QUIZ_TYPE")
    public Long getQuizType() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ANSWER</code>.
     */
    public void setAnswer(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ANSWER</code>.
     */
    @Column(name = "ANSWER")
    public String getAnswer() {
        return (String) get(5);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.DESCRIPTION</code>.
     */
    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.QUIZ_STATUS</code>.
     */
    public void setQuizStatus(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.QUIZ_STATUS</code>.
     */
    @Column(name = "QUIZ_STATUS")
    public Long getQuizStatus() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ORDER</code>.
     */
    public void setOrder(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ORDER</code>.
     */
    @Column(name = "ORDER")
    public Integer getOrder() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, String, String, Long, String, String, Long, Integer, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, String, String, Long, String, String, Long, Integer, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OtQuiz.OT_QUIZ.ID_QUIZ;
    }

    @Override
    public Field<Long> field2() {
        return OtQuiz.OT_QUIZ.ID_EXERCISE;
    }

    @Override
    public Field<String> field3() {
        return OtQuiz.OT_QUIZ.CONTENT_QUIZ;
    }

    @Override
    public Field<String> field4() {
        return OtQuiz.OT_QUIZ.OPTIONS;
    }

    @Override
    public Field<Long> field5() {
        return OtQuiz.OT_QUIZ.QUIZ_TYPE;
    }

    @Override
    public Field<String> field6() {
        return OtQuiz.OT_QUIZ.ANSWER;
    }

    @Override
    public Field<String> field7() {
        return OtQuiz.OT_QUIZ.DESCRIPTION;
    }

    @Override
    public Field<Long> field8() {
        return OtQuiz.OT_QUIZ.QUIZ_STATUS;
    }

    @Override
    public Field<Integer> field9() {
        return OtQuiz.OT_QUIZ.ORDER;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return OtQuiz.OT_QUIZ.CREATED_DATE;
    }

    @Override
    public Field<String> field11() {
        return OtQuiz.OT_QUIZ.LAST_MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return OtQuiz.OT_QUIZ.LAST_MODIFIED_DATE;
    }

    @Override
    public Long component1() {
        return getIdQuiz();
    }

    @Override
    public Long component2() {
        return getIdExercise();
    }

    @Override
    public String component3() {
        return getContentQuiz();
    }

    @Override
    public String component4() {
        return getOptions();
    }

    @Override
    public Long component5() {
        return getQuizType();
    }

    @Override
    public String component6() {
        return getAnswer();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public Long component8() {
        return getQuizStatus();
    }

    @Override
    public Integer component9() {
        return getOrder();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedDate();
    }

    @Override
    public String component11() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime component12() {
        return getLastModifiedDate();
    }

    @Override
    public Long value1() {
        return getIdQuiz();
    }

    @Override
    public Long value2() {
        return getIdExercise();
    }

    @Override
    public String value3() {
        return getContentQuiz();
    }

    @Override
    public String value4() {
        return getOptions();
    }

    @Override
    public Long value5() {
        return getQuizType();
    }

    @Override
    public String value6() {
        return getAnswer();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public Long value8() {
        return getQuizStatus();
    }

    @Override
    public Integer value9() {
        return getOrder();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedDate();
    }

    @Override
    public String value11() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime value12() {
        return getLastModifiedDate();
    }

    @Override
    public OtQuizRecord value1(Long value) {
        setIdQuiz(value);
        return this;
    }

    @Override
    public OtQuizRecord value2(Long value) {
        setIdExercise(value);
        return this;
    }

    @Override
    public OtQuizRecord value3(String value) {
        setContentQuiz(value);
        return this;
    }

    @Override
    public OtQuizRecord value4(String value) {
        setOptions(value);
        return this;
    }

    @Override
    public OtQuizRecord value5(Long value) {
        setQuizType(value);
        return this;
    }

    @Override
    public OtQuizRecord value6(String value) {
        setAnswer(value);
        return this;
    }

    @Override
    public OtQuizRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public OtQuizRecord value8(Long value) {
        setQuizStatus(value);
        return this;
    }

    @Override
    public OtQuizRecord value9(Integer value) {
        setOrder(value);
        return this;
    }

    @Override
    public OtQuizRecord value10(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public OtQuizRecord value11(String value) {
        setLastModifiedBy(value);
        return this;
    }

    @Override
    public OtQuizRecord value12(LocalDateTime value) {
        setLastModifiedDate(value);
        return this;
    }

    @Override
    public OtQuizRecord values(Long value1, Long value2, String value3, String value4, Long value5, String value6, String value7, Long value8, Integer value9, LocalDateTime value10, String value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OtQuizRecord
     */
    public OtQuizRecord() {
        super(OtQuiz.OT_QUIZ);
    }

    /**
     * Create a detached, initialised OtQuizRecord
     */
    public OtQuizRecord(Long idQuiz, Long idExercise, String contentQuiz, String options, Long quizType, String answer, String description, Long quizStatus, Integer order, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate) {
        super(OtQuiz.OT_QUIZ);

        setIdQuiz(idQuiz);
        setIdExercise(idExercise);
        setContentQuiz(contentQuiz);
        setOptions(options);
        setQuizType(quizType);
        setAnswer(answer);
        setDescription(description);
        setQuizStatus(quizStatus);
        setOrder(order);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
    }

    /**
     * Create a detached, initialised OtQuizRecord
     */
    public OtQuizRecord(cfm.onthi.entities.tables.pojos.OtQuiz value) {
        super(OtQuiz.OT_QUIZ);

        if (value != null) {
            setIdQuiz(value.getIdQuiz());
            setIdExercise(value.getIdExercise());
            setContentQuiz(value.getContentQuiz());
            setOptions(value.getOptions());
            setQuizType(value.getQuizType());
            setAnswer(value.getAnswer());
            setDescription(value.getDescription());
            setQuizStatus(value.getQuizStatus());
            setOrder(value.getOrder());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
        }
    }
}
