/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.records;


import cfm.onthi.entities.tables.OtQuiz;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_quiz",
    schema = "s_onthi"
)
public class OtQuizRecord extends UpdatableRecordImpl<OtQuizRecord> implements Record6<Long, Long, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    public void setIdQuiz(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_QUIZ", nullable = false)
    public Long getIdQuiz() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_LESSON</code>.
     */
    public void setIdLesson(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_LESSON</code>.
     */
    @Column(name = "ID_LESSON", nullable = false)
    public Long getIdLesson() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    public void setContentQuiz(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    @Column(name = "CONTENT_QUIZ", nullable = false, length = 2000)
    public String getContentQuiz() {
        return (String) get(2);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OtQuiz.OT_QUIZ.ID_QUIZ;
    }

    @Override
    public Field<Long> field2() {
        return OtQuiz.OT_QUIZ.ID_LESSON;
    }

    @Override
    public Field<String> field3() {
        return OtQuiz.OT_QUIZ.CONTENT_QUIZ;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return OtQuiz.OT_QUIZ.CREATED_DATE;
    }

    @Override
    public Field<String> field5() {
        return OtQuiz.OT_QUIZ.LAST_MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return OtQuiz.OT_QUIZ.LAST_MODIFIED_DATE;
    }

    @Override
    public Long component1() {
        return getIdQuiz();
    }

    @Override
    public Long component2() {
        return getIdLesson();
    }

    @Override
    public String component3() {
        return getContentQuiz();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedDate();
    }

    @Override
    public String component5() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime component6() {
        return getLastModifiedDate();
    }

    @Override
    public Long value1() {
        return getIdQuiz();
    }

    @Override
    public Long value2() {
        return getIdLesson();
    }

    @Override
    public String value3() {
        return getContentQuiz();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedDate();
    }

    @Override
    public String value5() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime value6() {
        return getLastModifiedDate();
    }

    @Override
    public OtQuizRecord value1(Long value) {
        setIdQuiz(value);
        return this;
    }

    @Override
    public OtQuizRecord value2(Long value) {
        setIdLesson(value);
        return this;
    }

    @Override
    public OtQuizRecord value3(String value) {
        setContentQuiz(value);
        return this;
    }

    @Override
    public OtQuizRecord value4(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public OtQuizRecord value5(String value) {
        setLastModifiedBy(value);
        return this;
    }

    @Override
    public OtQuizRecord value6(LocalDateTime value) {
        setLastModifiedDate(value);
        return this;
    }

    @Override
    public OtQuizRecord values(Long value1, Long value2, String value3, LocalDateTime value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OtQuizRecord
     */
    public OtQuizRecord() {
        super(OtQuiz.OT_QUIZ);
    }

    /**
     * Create a detached, initialised OtQuizRecord
     */
    public OtQuizRecord(Long idQuiz, Long idLesson, String contentQuiz, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate) {
        super(OtQuiz.OT_QUIZ);

        setIdQuiz(idQuiz);
        setIdLesson(idLesson);
        setContentQuiz(contentQuiz);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
    }

    /**
     * Create a detached, initialised OtQuizRecord
     */
    public OtQuizRecord(cfm.onthi.entities.tables.pojos.OtQuiz value) {
        super(OtQuiz.OT_QUIZ);

        if (value != null) {
            setIdQuiz(value.getIdQuiz());
            setIdLesson(value.getIdLesson());
            setContentQuiz(value.getContentQuiz());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
        }
    }
}
