/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.records;


import cfm.onthi.entities.tables.OtQuiz;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_quiz",
    schema = "s_onthi",
    indexes = {
        @Index(name = "ID_LESSON", columnList = "ID_LESSON ASC")
    }
)
public class OtQuizRecord extends UpdatableRecordImpl<OtQuizRecord> implements Record10<Long, Long, String, Long, String, Long, Integer, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    public void setIdQuiz(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_QUIZ", nullable = false)
    public Long getIdQuiz() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_LESSON</code>.
     */
    public void setIdLesson(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_LESSON</code>.
     */
    @Column(name = "ID_LESSON", nullable = false)
    public Long getIdLesson() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    public void setContentQuiz(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    @Column(name = "CONTENT_QUIZ", nullable = false, length = 2000)
    public String getContentQuiz() {
        return (String) get(2);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.QUIZ_TYPE</code>.
     */
    public void setQuizType(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.QUIZ_TYPE</code>.
     */
    @Column(name = "QUIZ_TYPE")
    public Long getQuizType() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ANSWER</code>.
     */
    public void setAnswer(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ANSWER</code>.
     */
    @Column(name = "ANSWER")
    public String getAnswer() {
        return (String) get(4);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.QUIZ_STATUS</code>.
     */
    public void setQuizStatus(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.QUIZ_STATUS</code>.
     */
    @Column(name = "QUIZ_STATUS")
    public Long getQuizStatus() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ORDER</code>.
     */
    public void setOrder(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ORDER</code>.
     */
    @Column(name = "ORDER")
    public Integer getOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, String, Long, String, Long, Integer, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, String, Long, String, Long, Integer, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OtQuiz.OT_QUIZ.ID_QUIZ;
    }

    @Override
    public Field<Long> field2() {
        return OtQuiz.OT_QUIZ.ID_LESSON;
    }

    @Override
    public Field<String> field3() {
        return OtQuiz.OT_QUIZ.CONTENT_QUIZ;
    }

    @Override
    public Field<Long> field4() {
        return OtQuiz.OT_QUIZ.QUIZ_TYPE;
    }

    @Override
    public Field<String> field5() {
        return OtQuiz.OT_QUIZ.ANSWER;
    }

    @Override
    public Field<Long> field6() {
        return OtQuiz.OT_QUIZ.QUIZ_STATUS;
    }

    @Override
    public Field<Integer> field7() {
        return OtQuiz.OT_QUIZ.ORDER;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return OtQuiz.OT_QUIZ.CREATED_DATE;
    }

    @Override
    public Field<String> field9() {
        return OtQuiz.OT_QUIZ.LAST_MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return OtQuiz.OT_QUIZ.LAST_MODIFIED_DATE;
    }

    @Override
    public Long component1() {
        return getIdQuiz();
    }

    @Override
    public Long component2() {
        return getIdLesson();
    }

    @Override
    public String component3() {
        return getContentQuiz();
    }

    @Override
    public Long component4() {
        return getQuizType();
    }

    @Override
    public String component5() {
        return getAnswer();
    }

    @Override
    public Long component6() {
        return getQuizStatus();
    }

    @Override
    public Integer component7() {
        return getOrder();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedDate();
    }

    @Override
    public String component9() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime component10() {
        return getLastModifiedDate();
    }

    @Override
    public Long value1() {
        return getIdQuiz();
    }

    @Override
    public Long value2() {
        return getIdLesson();
    }

    @Override
    public String value3() {
        return getContentQuiz();
    }

    @Override
    public Long value4() {
        return getQuizType();
    }

    @Override
    public String value5() {
        return getAnswer();
    }

    @Override
    public Long value6() {
        return getQuizStatus();
    }

    @Override
    public Integer value7() {
        return getOrder();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedDate();
    }

    @Override
    public String value9() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime value10() {
        return getLastModifiedDate();
    }

    @Override
    public OtQuizRecord value1(Long value) {
        setIdQuiz(value);
        return this;
    }

    @Override
    public OtQuizRecord value2(Long value) {
        setIdLesson(value);
        return this;
    }

    @Override
    public OtQuizRecord value3(String value) {
        setContentQuiz(value);
        return this;
    }

    @Override
    public OtQuizRecord value4(Long value) {
        setQuizType(value);
        return this;
    }

    @Override
    public OtQuizRecord value5(String value) {
        setAnswer(value);
        return this;
    }

    @Override
    public OtQuizRecord value6(Long value) {
        setQuizStatus(value);
        return this;
    }

    @Override
    public OtQuizRecord value7(Integer value) {
        setOrder(value);
        return this;
    }

    @Override
    public OtQuizRecord value8(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public OtQuizRecord value9(String value) {
        setLastModifiedBy(value);
        return this;
    }

    @Override
    public OtQuizRecord value10(LocalDateTime value) {
        setLastModifiedDate(value);
        return this;
    }

    @Override
    public OtQuizRecord values(Long value1, Long value2, String value3, Long value4, String value5, Long value6, Integer value7, LocalDateTime value8, String value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OtQuizRecord
     */
    public OtQuizRecord() {
        super(OtQuiz.OT_QUIZ);
    }

    /**
     * Create a detached, initialised OtQuizRecord
     */
    public OtQuizRecord(Long idQuiz, Long idLesson, String contentQuiz, Long quizType, String answer, Long quizStatus, Integer order, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate) {
        super(OtQuiz.OT_QUIZ);

        setIdQuiz(idQuiz);
        setIdLesson(idLesson);
        setContentQuiz(contentQuiz);
        setQuizType(quizType);
        setAnswer(answer);
        setQuizStatus(quizStatus);
        setOrder(order);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
    }

    /**
     * Create a detached, initialised OtQuizRecord
     */
    public OtQuizRecord(cfm.onthi.entities.tables.pojos.OtQuiz value) {
        super(OtQuiz.OT_QUIZ);

        if (value != null) {
            setIdQuiz(value.getIdQuiz());
            setIdLesson(value.getIdLesson());
            setContentQuiz(value.getContentQuiz());
            setQuizType(value.getQuizType());
            setAnswer(value.getAnswer());
            setQuizStatus(value.getQuizStatus());
            setOrder(value.getOrder());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
        }
    }
}
