/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.records;


import cfm.onthi.entities.tables.OtReview;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_review",
    schema = "s_onthi"
)
public class OtReviewRecord extends UpdatableRecordImpl<OtReviewRecord> implements Record7<Long, Long, Long, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>s_onthi.ot_review.ID_REVIEW</code>.
     */
    public void setIdReview(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>s_onthi.ot_review.ID_REVIEW</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_REVIEW", nullable = false)
    public Long getIdReview() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>s_onthi.ot_review.ID_COURSE</code>.
     */
    public void setIdCourse(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>s_onthi.ot_review.ID_COURSE</code>.
     */
    @Column(name = "ID_COURSE", nullable = false)
    public Long getIdCourse() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>s_onthi.ot_review.ID_USER</code>.
     */
    public void setIdUser(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>s_onthi.ot_review.ID_USER</code>.
     */
    @Column(name = "ID_USER", nullable = false)
    public Long getIdUser() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>s_onthi.ot_review.CONTENT</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>s_onthi.ot_review.CONTENT</code>.
     */
    @Column(name = "CONTENT", nullable = false, length = 2000)
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>s_onthi.ot_review.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>s_onthi.ot_review.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>s_onthi.ot_review.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>s_onthi.ot_review.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>s_onthi.ot_review.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>s_onthi.ot_review.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OtReview.OT_REVIEW.ID_REVIEW;
    }

    @Override
    public Field<Long> field2() {
        return OtReview.OT_REVIEW.ID_COURSE;
    }

    @Override
    public Field<Long> field3() {
        return OtReview.OT_REVIEW.ID_USER;
    }

    @Override
    public Field<String> field4() {
        return OtReview.OT_REVIEW.CONTENT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return OtReview.OT_REVIEW.CREATED_DATE;
    }

    @Override
    public Field<String> field6() {
        return OtReview.OT_REVIEW.LAST_MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return OtReview.OT_REVIEW.LAST_MODIFIED_DATE;
    }

    @Override
    public Long component1() {
        return getIdReview();
    }

    @Override
    public Long component2() {
        return getIdCourse();
    }

    @Override
    public Long component3() {
        return getIdUser();
    }

    @Override
    public String component4() {
        return getContent();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public String component6() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getLastModifiedDate();
    }

    @Override
    public Long value1() {
        return getIdReview();
    }

    @Override
    public Long value2() {
        return getIdCourse();
    }

    @Override
    public Long value3() {
        return getIdUser();
    }

    @Override
    public String value4() {
        return getContent();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public String value6() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getLastModifiedDate();
    }

    @Override
    public OtReviewRecord value1(Long value) {
        setIdReview(value);
        return this;
    }

    @Override
    public OtReviewRecord value2(Long value) {
        setIdCourse(value);
        return this;
    }

    @Override
    public OtReviewRecord value3(Long value) {
        setIdUser(value);
        return this;
    }

    @Override
    public OtReviewRecord value4(String value) {
        setContent(value);
        return this;
    }

    @Override
    public OtReviewRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public OtReviewRecord value6(String value) {
        setLastModifiedBy(value);
        return this;
    }

    @Override
    public OtReviewRecord value7(LocalDateTime value) {
        setLastModifiedDate(value);
        return this;
    }

    @Override
    public OtReviewRecord values(Long value1, Long value2, Long value3, String value4, LocalDateTime value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OtReviewRecord
     */
    public OtReviewRecord() {
        super(OtReview.OT_REVIEW);
    }

    /**
     * Create a detached, initialised OtReviewRecord
     */
    public OtReviewRecord(Long idReview, Long idCourse, Long idUser, String content, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate) {
        super(OtReview.OT_REVIEW);

        setIdReview(idReview);
        setIdCourse(idCourse);
        setIdUser(idUser);
        setContent(content);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
    }

    /**
     * Create a detached, initialised OtReviewRecord
     */
    public OtReviewRecord(cfm.onthi.entities.tables.pojos.OtReview value) {
        super(OtReview.OT_REVIEW);

        if (value != null) {
            setIdReview(value.getIdReview());
            setIdCourse(value.getIdCourse());
            setIdUser(value.getIdUser());
            setContent(value.getContent());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
        }
    }
}
