/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.records;


import cfm.onthi.entities.tables.OtSchool;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_school",
    schema = "s_onthi"
)
public class OtSchoolRecord extends UpdatableRecordImpl<OtSchoolRecord> implements Record7<Long, Long, String, Long, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>s_onthi.ot_school.ID_SCHOOL</code>.
     */
    public void setIdSchool(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>s_onthi.ot_school.ID_SCHOOL</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_SCHOOL", nullable = false)
    public Long getIdSchool() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>s_onthi.ot_school.ID_PROVINCE</code>.
     */
    public void setIdProvince(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>s_onthi.ot_school.ID_PROVINCE</code>.
     */
    @Column(name = "ID_PROVINCE")
    public Long getIdProvince() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>s_onthi.ot_school.SCHOOL_NAME</code>.
     */
    public void setSchoolName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>s_onthi.ot_school.SCHOOL_NAME</code>.
     */
    @Column(name = "SCHOOL_NAME", nullable = false, length = 50)
    public String getSchoolName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>s_onthi.ot_school.TYPE_SCHOOL</code>.
     */
    public void setTypeSchool(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>s_onthi.ot_school.TYPE_SCHOOL</code>.
     */
    @Column(name = "TYPE_SCHOOL")
    public Long getTypeSchool() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>s_onthi.ot_school.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>s_onthi.ot_school.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>s_onthi.ot_school.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>s_onthi.ot_school.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>s_onthi.ot_school.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>s_onthi.ot_school.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, Long, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, String, Long, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OtSchool.OT_SCHOOL.ID_SCHOOL;
    }

    @Override
    public Field<Long> field2() {
        return OtSchool.OT_SCHOOL.ID_PROVINCE;
    }

    @Override
    public Field<String> field3() {
        return OtSchool.OT_SCHOOL.SCHOOL_NAME;
    }

    @Override
    public Field<Long> field4() {
        return OtSchool.OT_SCHOOL.TYPE_SCHOOL;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return OtSchool.OT_SCHOOL.CREATED_DATE;
    }

    @Override
    public Field<String> field6() {
        return OtSchool.OT_SCHOOL.LAST_MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return OtSchool.OT_SCHOOL.LAST_MODIFIED_DATE;
    }

    @Override
    public Long component1() {
        return getIdSchool();
    }

    @Override
    public Long component2() {
        return getIdProvince();
    }

    @Override
    public String component3() {
        return getSchoolName();
    }

    @Override
    public Long component4() {
        return getTypeSchool();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public String component6() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getLastModifiedDate();
    }

    @Override
    public Long value1() {
        return getIdSchool();
    }

    @Override
    public Long value2() {
        return getIdProvince();
    }

    @Override
    public String value3() {
        return getSchoolName();
    }

    @Override
    public Long value4() {
        return getTypeSchool();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public String value6() {
        return getLastModifiedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getLastModifiedDate();
    }

    @Override
    public OtSchoolRecord value1(Long value) {
        setIdSchool(value);
        return this;
    }

    @Override
    public OtSchoolRecord value2(Long value) {
        setIdProvince(value);
        return this;
    }

    @Override
    public OtSchoolRecord value3(String value) {
        setSchoolName(value);
        return this;
    }

    @Override
    public OtSchoolRecord value4(Long value) {
        setTypeSchool(value);
        return this;
    }

    @Override
    public OtSchoolRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public OtSchoolRecord value6(String value) {
        setLastModifiedBy(value);
        return this;
    }

    @Override
    public OtSchoolRecord value7(LocalDateTime value) {
        setLastModifiedDate(value);
        return this;
    }

    @Override
    public OtSchoolRecord values(Long value1, Long value2, String value3, Long value4, LocalDateTime value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OtSchoolRecord
     */
    public OtSchoolRecord() {
        super(OtSchool.OT_SCHOOL);
    }

    /**
     * Create a detached, initialised OtSchoolRecord
     */
    public OtSchoolRecord(Long idSchool, Long idProvince, String schoolName, Long typeSchool, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate) {
        super(OtSchool.OT_SCHOOL);

        setIdSchool(idSchool);
        setIdProvince(idProvince);
        setSchoolName(schoolName);
        setTypeSchool(typeSchool);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
    }

    /**
     * Create a detached, initialised OtSchoolRecord
     */
    public OtSchoolRecord(cfm.onthi.entities.tables.pojos.OtSchool value) {
        super(OtSchool.OT_SCHOOL);

        if (value != null) {
            setIdSchool(value.getIdSchool());
            setIdProvince(value.getIdProvince());
            setSchoolName(value.getSchoolName());
            setTypeSchool(value.getTypeSchool());
            setCreatedDate(value.getCreatedDate());
            setLastModifiedBy(value.getLastModifiedBy());
            setLastModifiedDate(value.getLastModifiedDate());
        }
    }
}
