/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.records;


import cfm.onthi.entities.tables.OtUserCourse;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_user_course",
    schema = "s_onthi",
    indexes = {
        @Index(name = "ID_COURSE", columnList = "ID_COURSE ASC"),
        @Index(name = "ID_USER", columnList = "ID_USER ASC")
    }
)
public class OtUserCourseRecord extends UpdatableRecordImpl<OtUserCourseRecord> implements Record6<Long, Long, Long, Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_USER_COURSE</code>.
     */
    public void setIdUserCourse(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_USER_COURSE</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_USER_COURSE", nullable = false)
    public Long getIdUserCourse() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_USER</code>.
     */
    public void setIdUser(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_USER</code>.
     */
    @Column(name = "ID_USER", nullable = false)
    public Long getIdUser() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_COURSE</code>.
     */
    public void setIdCourse(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_COURSE</code>.
     */
    @Column(name = "ID_COURSE", nullable = false)
    public Long getIdCourse() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.LEARNING_LESSON</code>.
     */
    public void setLearningLesson(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.LEARNING_LESSON</code>.
     */
    @Column(name = "LEARNING_LESSON")
    public Long getLearningLesson() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.LEARNED_LESSON</code>.
     */
    public void setLearnedLesson(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.LEARNED_LESSON</code>.
     */
    @Column(name = "LEARNED_LESSON", length = 5000)
    public String getLearnedLesson() {
        return (String) get(4);
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.TIME_SCHEDULE</code>.
     */
    public void setTimeSchedule(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.TIME_SCHEDULE</code>.
     */
    @Column(name = "TIME_SCHEDULE", length = 50)
    public String getTimeSchedule() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OtUserCourse.OT_USER_COURSE.ID_USER_COURSE;
    }

    @Override
    public Field<Long> field2() {
        return OtUserCourse.OT_USER_COURSE.ID_USER;
    }

    @Override
    public Field<Long> field3() {
        return OtUserCourse.OT_USER_COURSE.ID_COURSE;
    }

    @Override
    public Field<Long> field4() {
        return OtUserCourse.OT_USER_COURSE.LEARNING_LESSON;
    }

    @Override
    public Field<String> field5() {
        return OtUserCourse.OT_USER_COURSE.LEARNED_LESSON;
    }

    @Override
    public Field<String> field6() {
        return OtUserCourse.OT_USER_COURSE.TIME_SCHEDULE;
    }

    @Override
    public Long component1() {
        return getIdUserCourse();
    }

    @Override
    public Long component2() {
        return getIdUser();
    }

    @Override
    public Long component3() {
        return getIdCourse();
    }

    @Override
    public Long component4() {
        return getLearningLesson();
    }

    @Override
    public String component5() {
        return getLearnedLesson();
    }

    @Override
    public String component6() {
        return getTimeSchedule();
    }

    @Override
    public Long value1() {
        return getIdUserCourse();
    }

    @Override
    public Long value2() {
        return getIdUser();
    }

    @Override
    public Long value3() {
        return getIdCourse();
    }

    @Override
    public Long value4() {
        return getLearningLesson();
    }

    @Override
    public String value5() {
        return getLearnedLesson();
    }

    @Override
    public String value6() {
        return getTimeSchedule();
    }

    @Override
    public OtUserCourseRecord value1(Long value) {
        setIdUserCourse(value);
        return this;
    }

    @Override
    public OtUserCourseRecord value2(Long value) {
        setIdUser(value);
        return this;
    }

    @Override
    public OtUserCourseRecord value3(Long value) {
        setIdCourse(value);
        return this;
    }

    @Override
    public OtUserCourseRecord value4(Long value) {
        setLearningLesson(value);
        return this;
    }

    @Override
    public OtUserCourseRecord value5(String value) {
        setLearnedLesson(value);
        return this;
    }

    @Override
    public OtUserCourseRecord value6(String value) {
        setTimeSchedule(value);
        return this;
    }

    @Override
    public OtUserCourseRecord values(Long value1, Long value2, Long value3, Long value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OtUserCourseRecord
     */
    public OtUserCourseRecord() {
        super(OtUserCourse.OT_USER_COURSE);
    }

    /**
     * Create a detached, initialised OtUserCourseRecord
     */
    public OtUserCourseRecord(Long idUserCourse, Long idUser, Long idCourse, Long learningLesson, String learnedLesson, String timeSchedule) {
        super(OtUserCourse.OT_USER_COURSE);

        setIdUserCourse(idUserCourse);
        setIdUser(idUser);
        setIdCourse(idCourse);
        setLearningLesson(learningLesson);
        setLearnedLesson(learnedLesson);
        setTimeSchedule(timeSchedule);
    }

    /**
     * Create a detached, initialised OtUserCourseRecord
     */
    public OtUserCourseRecord(cfm.onthi.entities.tables.pojos.OtUserCourse value) {
        super(OtUserCourse.OT_USER_COURSE);

        if (value != null) {
            setIdUserCourse(value.getIdUserCourse());
            setIdUser(value.getIdUser());
            setIdCourse(value.getIdCourse());
            setLearningLesson(value.getLearningLesson());
            setLearnedLesson(value.getLearnedLesson());
            setTimeSchedule(value.getTimeSchedule());
        }
    }
}
