/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables;


import cfm.onthi.entities.Keys;
import cfm.onthi.entities.SOnthi;
import cfm.onthi.entities.tables.records.OtProvinceRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OtProvince extends TableImpl<OtProvinceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s_onthi.ot_province</code>
     */
    public static final OtProvince OT_PROVINCE = new OtProvince();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OtProvinceRecord> getRecordType() {
        return OtProvinceRecord.class;
    }

    /**
     * The column <code>s_onthi.ot_province.ID_PROVINCE</code>.
     */
    public final TableField<OtProvinceRecord, Long> ID_PROVINCE = createField(DSL.name("ID_PROVINCE"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>s_onthi.ot_province.PROVINCE_NAME</code>.
     */
    public final TableField<OtProvinceRecord, String> PROVINCE_NAME = createField(DSL.name("PROVINCE_NAME"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private OtProvince(Name alias, Table<OtProvinceRecord> aliased) {
        this(alias, aliased, null);
    }

    private OtProvince(Name alias, Table<OtProvinceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>s_onthi.ot_province</code> table reference
     */
    public OtProvince(String alias) {
        this(DSL.name(alias), OT_PROVINCE);
    }

    /**
     * Create an aliased <code>s_onthi.ot_province</code> table reference
     */
    public OtProvince(Name alias) {
        this(alias, OT_PROVINCE);
    }

    /**
     * Create a <code>s_onthi.ot_province</code> table reference
     */
    public OtProvince() {
        this(DSL.name("ot_province"), null);
    }

    public <O extends Record> OtProvince(Table<O> child, ForeignKey<O, OtProvinceRecord> key) {
        super(child, key, OT_PROVINCE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SOnthi.S_ONTHI;
    }

    @Override
    public Identity<OtProvinceRecord, Long> getIdentity() {
        return (Identity<OtProvinceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OtProvinceRecord> getPrimaryKey() {
        return Keys.KEY_OT_PROVINCE_PRIMARY;
    }

    @Override
    public OtProvince as(String alias) {
        return new OtProvince(DSL.name(alias), this);
    }

    @Override
    public OtProvince as(Name alias) {
        return new OtProvince(alias, this);
    }

    @Override
    public OtProvince as(Table<?> alias) {
        return new OtProvince(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OtProvince rename(String name) {
        return new OtProvince(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OtProvince rename(Name name) {
        return new OtProvince(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OtProvince rename(Table<?> name) {
        return new OtProvince(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
