/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables;


import cfm.onthi.entities.Keys;
import cfm.onthi.entities.SOnthi;
import cfm.onthi.entities.tables.records.OtSchoolRecord;

import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OtSchool extends TableImpl<OtSchoolRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s_onthi.ot_school</code>
     */
    public static final OtSchool OT_SCHOOL = new OtSchool();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OtSchoolRecord> getRecordType() {
        return OtSchoolRecord.class;
    }

    /**
     * The column <code>s_onthi.ot_school.ID_SCHOOL</code>.
     */
    public final TableField<OtSchoolRecord, Long> ID_SCHOOL = createField(DSL.name("ID_SCHOOL"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>s_onthi.ot_school.ID_PROVINCE</code>.
     */
    public final TableField<OtSchoolRecord, Long> ID_PROVINCE = createField(DSL.name("ID_PROVINCE"), SQLDataType.BIGINT.defaultValue(DSL.field("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>s_onthi.ot_school.SCHOOL_NAME</code>.
     */
    public final TableField<OtSchoolRecord, String> SCHOOL_NAME = createField(DSL.name("SCHOOL_NAME"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>s_onthi.ot_school.TYPE_SCHOOL</code>.
     */
    public final TableField<OtSchoolRecord, Long> TYPE_SCHOOL = createField(DSL.name("TYPE_SCHOOL"), SQLDataType.BIGINT.defaultValue(DSL.field("NULL", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>s_onthi.ot_school.CREATED_DATE</code>.
     */
    public final TableField<OtSchoolRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("CREATED_DATE"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("NULL", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>s_onthi.ot_school.LAST_MODIFIED_BY</code>.
     */
    public final TableField<OtSchoolRecord, String> LAST_MODIFIED_BY = createField(DSL.name("LAST_MODIFIED_BY"), SQLDataType.VARCHAR(50).defaultValue(DSL.field("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>s_onthi.ot_school.LAST_MODIFIED_DATE</code>.
     */
    public final TableField<OtSchoolRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("LAST_MODIFIED_DATE"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("NULL", SQLDataType.LOCALDATETIME)), this, "");

    private OtSchool(Name alias, Table<OtSchoolRecord> aliased) {
        this(alias, aliased, null);
    }

    private OtSchool(Name alias, Table<OtSchoolRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>s_onthi.ot_school</code> table reference
     */
    public OtSchool(String alias) {
        this(DSL.name(alias), OT_SCHOOL);
    }

    /**
     * Create an aliased <code>s_onthi.ot_school</code> table reference
     */
    public OtSchool(Name alias) {
        this(alias, OT_SCHOOL);
    }

    /**
     * Create a <code>s_onthi.ot_school</code> table reference
     */
    public OtSchool() {
        this(DSL.name("ot_school"), null);
    }

    public <O extends Record> OtSchool(Table<O> child, ForeignKey<O, OtSchoolRecord> key) {
        super(child, key, OT_SCHOOL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SOnthi.S_ONTHI;
    }

    @Override
    public Identity<OtSchoolRecord, Long> getIdentity() {
        return (Identity<OtSchoolRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OtSchoolRecord> getPrimaryKey() {
        return Keys.KEY_OT_SCHOOL_PRIMARY;
    }

    @Override
    public OtSchool as(String alias) {
        return new OtSchool(DSL.name(alias), this);
    }

    @Override
    public OtSchool as(Name alias) {
        return new OtSchool(alias, this);
    }

    @Override
    public OtSchool as(Table<?> alias) {
        return new OtSchool(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OtSchool rename(String name) {
        return new OtSchool(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OtSchool rename(Name name) {
        return new OtSchool(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OtSchool rename(Table<?> name) {
        return new OtSchool(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, Long, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super Long, ? super String, ? super Long, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super Long, ? super String, ? super Long, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
