/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables;


import cfm.onthi.entities.Keys;
import cfm.onthi.entities.SOnthi;
import cfm.onthi.entities.tables.records.OtUserRoleRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OtUserRole extends TableImpl<OtUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s_onthi.ot_user_role</code>
     */
    public static final OtUserRole OT_USER_ROLE = new OtUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OtUserRoleRecord> getRecordType() {
        return OtUserRoleRecord.class;
    }

    /**
     * The column <code>s_onthi.ot_user_role.ID</code>.
     */
    public final TableField<OtUserRoleRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>s_onthi.ot_user_role.ID_USER</code>.
     */
    public final TableField<OtUserRoleRecord, Long> ID_USER = createField(DSL.name("ID_USER"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>s_onthi.ot_user_role.ID_ROLE</code>.
     */
    public final TableField<OtUserRoleRecord, Long> ID_ROLE = createField(DSL.name("ID_ROLE"), SQLDataType.BIGINT.nullable(false), this, "");

    private OtUserRole(Name alias, Table<OtUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private OtUserRole(Name alias, Table<OtUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>s_onthi.ot_user_role</code> table reference
     */
    public OtUserRole(String alias) {
        this(DSL.name(alias), OT_USER_ROLE);
    }

    /**
     * Create an aliased <code>s_onthi.ot_user_role</code> table reference
     */
    public OtUserRole(Name alias) {
        this(alias, OT_USER_ROLE);
    }

    /**
     * Create a <code>s_onthi.ot_user_role</code> table reference
     */
    public OtUserRole() {
        this(DSL.name("ot_user_role"), null);
    }

    public <O extends Record> OtUserRole(Table<O> child, ForeignKey<O, OtUserRoleRecord> key) {
        super(child, key, OT_USER_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SOnthi.S_ONTHI;
    }

    @Override
    public Identity<OtUserRoleRecord, Long> getIdentity() {
        return (Identity<OtUserRoleRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OtUserRoleRecord> getPrimaryKey() {
        return Keys.KEY_OT_USER_ROLE_PRIMARY;
    }

    @Override
    public List<UniqueKey<OtUserRoleRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_OT_USER_ROLE_ID_USER, Keys.KEY_OT_USER_ROLE_ID_ROLE);
    }

    @Override
    public OtUserRole as(String alias) {
        return new OtUserRole(DSL.name(alias), this);
    }

    @Override
    public OtUserRole as(Name alias) {
        return new OtUserRole(alias, this);
    }

    @Override
    public OtUserRole as(Table<?> alias) {
        return new OtUserRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OtUserRole rename(String name) {
        return new OtUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OtUserRole rename(Name name) {
        return new OtUserRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OtUserRole rename(Table<?> name) {
        return new OtUserRole(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
