/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_quiz",
    schema = "s_onthi"
)
public class OtQuiz implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long idQuiz;
    private Long idExercise;
    private String contentQuiz;
    private String options;
    private Long quizType;
    private String answer;
    private String description;
    private Long quizStatus;
    private Integer order;
    private LocalDateTime createdDate;
    private String lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public OtQuiz() {}

    public OtQuiz(OtQuiz value) {
        this.idQuiz = value.idQuiz;
        this.idExercise = value.idExercise;
        this.contentQuiz = value.contentQuiz;
        this.options = value.options;
        this.quizType = value.quizType;
        this.answer = value.answer;
        this.description = value.description;
        this.quizStatus = value.quizStatus;
        this.order = value.order;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public OtQuiz(
        Long idQuiz,
        Long idExercise,
        String contentQuiz,
        String options,
        Long quizType,
        String answer,
        String description,
        Long quizStatus,
        Integer order,
        LocalDateTime createdDate,
        String lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.idQuiz = idQuiz;
        this.idExercise = idExercise;
        this.contentQuiz = contentQuiz;
        this.options = options;
        this.quizType = quizType;
        this.answer = answer;
        this.description = description;
        this.quizStatus = quizStatus;
        this.order = order;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_QUIZ", nullable = false)
    public Long getIdQuiz() {
        return this.idQuiz;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    public void setIdQuiz(Long idQuiz) {
        this.idQuiz = idQuiz;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_EXERCISE</code>.
     */
    @Column(name = "ID_EXERCISE", nullable = false)
    public Long getIdExercise() {
        return this.idExercise;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_EXERCISE</code>.
     */
    public void setIdExercise(Long idExercise) {
        this.idExercise = idExercise;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    @Column(name = "CONTENT_QUIZ", nullable = false)
    public String getContentQuiz() {
        return this.contentQuiz;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    public void setContentQuiz(String contentQuiz) {
        this.contentQuiz = contentQuiz;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.OPTIONS</code>.
     */
    @Column(name = "OPTIONS")
    public String getOptions() {
        return this.options;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.OPTIONS</code>.
     */
    public void setOptions(String options) {
        this.options = options;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.QUIZ_TYPE</code>.
     */
    @Column(name = "QUIZ_TYPE")
    public Long getQuizType() {
        return this.quizType;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.QUIZ_TYPE</code>.
     */
    public void setQuizType(Long quizType) {
        this.quizType = quizType;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ANSWER</code>.
     */
    @Column(name = "ANSWER")
    public String getAnswer() {
        return this.answer;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ANSWER</code>.
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.DESCRIPTION</code>.
     */
    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.DESCRIPTION</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.QUIZ_STATUS</code>.
     */
    @Column(name = "QUIZ_STATUS")
    public Long getQuizStatus() {
        return this.quizStatus;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.QUIZ_STATUS</code>.
     */
    public void setQuizStatus(Long quizStatus) {
        this.quizStatus = quizStatus;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ORDER</code>.
     */
    @Column(name = "ORDER")
    public Integer getOrder() {
        return this.order;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ORDER</code>.
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OtQuiz other = (OtQuiz) obj;
        if (this.idQuiz == null) {
            if (other.idQuiz != null)
                return false;
        }
        else if (!this.idQuiz.equals(other.idQuiz))
            return false;
        if (this.idExercise == null) {
            if (other.idExercise != null)
                return false;
        }
        else if (!this.idExercise.equals(other.idExercise))
            return false;
        if (this.contentQuiz == null) {
            if (other.contentQuiz != null)
                return false;
        }
        else if (!this.contentQuiz.equals(other.contentQuiz))
            return false;
        if (this.options == null) {
            if (other.options != null)
                return false;
        }
        else if (!this.options.equals(other.options))
            return false;
        if (this.quizType == null) {
            if (other.quizType != null)
                return false;
        }
        else if (!this.quizType.equals(other.quizType))
            return false;
        if (this.answer == null) {
            if (other.answer != null)
                return false;
        }
        else if (!this.answer.equals(other.answer))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.quizStatus == null) {
            if (other.quizStatus != null)
                return false;
        }
        else if (!this.quizStatus.equals(other.quizStatus))
            return false;
        if (this.order == null) {
            if (other.order != null)
                return false;
        }
        else if (!this.order.equals(other.order))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idQuiz == null) ? 0 : this.idQuiz.hashCode());
        result = prime * result + ((this.idExercise == null) ? 0 : this.idExercise.hashCode());
        result = prime * result + ((this.contentQuiz == null) ? 0 : this.contentQuiz.hashCode());
        result = prime * result + ((this.options == null) ? 0 : this.options.hashCode());
        result = prime * result + ((this.quizType == null) ? 0 : this.quizType.hashCode());
        result = prime * result + ((this.answer == null) ? 0 : this.answer.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.quizStatus == null) ? 0 : this.quizStatus.hashCode());
        result = prime * result + ((this.order == null) ? 0 : this.order.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtQuiz (");

        sb.append(idQuiz);
        sb.append(", ").append(idExercise);
        sb.append(", ").append(contentQuiz);
        sb.append(", ").append(options);
        sb.append(", ").append(quizType);
        sb.append(", ").append(answer);
        sb.append(", ").append(description);
        sb.append(", ").append(quizStatus);
        sb.append(", ").append(order);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(lastModifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
