/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_quiz",
    schema = "s_onthi",
    indexes = {
        @Index(name = "ID_LESSON", columnList = "ID_LESSON ASC")
    }
)
public class OtQuiz implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long idQuiz;
    private Long idLesson;
    private String contentQuiz;
    private LocalDateTime createdDate;
    private String lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public OtQuiz() {}

    public OtQuiz(OtQuiz value) {
        this.idQuiz = value.idQuiz;
        this.idLesson = value.idLesson;
        this.contentQuiz = value.contentQuiz;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public OtQuiz(
        Long idQuiz,
        Long idLesson,
        String contentQuiz,
        LocalDateTime createdDate,
        String lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.idQuiz = idQuiz;
        this.idLesson = idLesson;
        this.contentQuiz = contentQuiz;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_QUIZ", nullable = false)
    public Long getIdQuiz() {
        return this.idQuiz;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_QUIZ</code>.
     */
    public void setIdQuiz(Long idQuiz) {
        this.idQuiz = idQuiz;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.ID_LESSON</code>.
     */
    @Column(name = "ID_LESSON", nullable = false)
    public Long getIdLesson() {
        return this.idLesson;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.ID_LESSON</code>.
     */
    public void setIdLesson(Long idLesson) {
        this.idLesson = idLesson;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    @Column(name = "CONTENT_QUIZ", nullable = false, length = 2000)
    public String getContentQuiz() {
        return this.contentQuiz;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CONTENT_QUIZ</code>.
     */
    public void setContentQuiz(String contentQuiz) {
        this.contentQuiz = contentQuiz;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>s_onthi.ot_quiz.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OtQuiz other = (OtQuiz) obj;
        if (this.idQuiz == null) {
            if (other.idQuiz != null)
                return false;
        }
        else if (!this.idQuiz.equals(other.idQuiz))
            return false;
        if (this.idLesson == null) {
            if (other.idLesson != null)
                return false;
        }
        else if (!this.idLesson.equals(other.idLesson))
            return false;
        if (this.contentQuiz == null) {
            if (other.contentQuiz != null)
                return false;
        }
        else if (!this.contentQuiz.equals(other.contentQuiz))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idQuiz == null) ? 0 : this.idQuiz.hashCode());
        result = prime * result + ((this.idLesson == null) ? 0 : this.idLesson.hashCode());
        result = prime * result + ((this.contentQuiz == null) ? 0 : this.contentQuiz.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtQuiz (");

        sb.append(idQuiz);
        sb.append(", ").append(idLesson);
        sb.append(", ").append(contentQuiz);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(lastModifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
