/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_role_menu",
    schema = "s_onthi",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_ot_role_menu_ID_ROLE", columnNames = { "ID_ROLE" }),
        @UniqueConstraint(name = "KEY_ot_role_menu_ID_MENU", columnNames = { "ID_MENU" })
    }
)
public class OtRoleMenu implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long idRoleMenu;
    private Long idRole;
    private Long idMenu;

    public OtRoleMenu() {}

    public OtRoleMenu(OtRoleMenu value) {
        this.idRoleMenu = value.idRoleMenu;
        this.idRole = value.idRole;
        this.idMenu = value.idMenu;
    }

    public OtRoleMenu(
        Long idRoleMenu,
        Long idRole,
        Long idMenu
    ) {
        this.idRoleMenu = idRoleMenu;
        this.idRole = idRole;
        this.idMenu = idMenu;
    }

    /**
     * Getter for <code>s_onthi.ot_role_menu.ID_ROLE_MENU</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_ROLE_MENU", nullable = false)
    public Long getIdRoleMenu() {
        return this.idRoleMenu;
    }

    /**
     * Setter for <code>s_onthi.ot_role_menu.ID_ROLE_MENU</code>.
     */
    public void setIdRoleMenu(Long idRoleMenu) {
        this.idRoleMenu = idRoleMenu;
    }

    /**
     * Getter for <code>s_onthi.ot_role_menu.ID_ROLE</code>.
     */
    @Column(name = "ID_ROLE", nullable = false)
    public Long getIdRole() {
        return this.idRole;
    }

    /**
     * Setter for <code>s_onthi.ot_role_menu.ID_ROLE</code>.
     */
    public void setIdRole(Long idRole) {
        this.idRole = idRole;
    }

    /**
     * Getter for <code>s_onthi.ot_role_menu.ID_MENU</code>.
     */
    @Column(name = "ID_MENU", nullable = false)
    public Long getIdMenu() {
        return this.idMenu;
    }

    /**
     * Setter for <code>s_onthi.ot_role_menu.ID_MENU</code>.
     */
    public void setIdMenu(Long idMenu) {
        this.idMenu = idMenu;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OtRoleMenu other = (OtRoleMenu) obj;
        if (this.idRoleMenu == null) {
            if (other.idRoleMenu != null)
                return false;
        }
        else if (!this.idRoleMenu.equals(other.idRoleMenu))
            return false;
        if (this.idRole == null) {
            if (other.idRole != null)
                return false;
        }
        else if (!this.idRole.equals(other.idRole))
            return false;
        if (this.idMenu == null) {
            if (other.idMenu != null)
                return false;
        }
        else if (!this.idMenu.equals(other.idMenu))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idRoleMenu == null) ? 0 : this.idRoleMenu.hashCode());
        result = prime * result + ((this.idRole == null) ? 0 : this.idRole.hashCode());
        result = prime * result + ((this.idMenu == null) ? 0 : this.idMenu.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtRoleMenu (");

        sb.append(idRoleMenu);
        sb.append(", ").append(idRole);
        sb.append(", ").append(idMenu);

        sb.append(")");
        return sb.toString();
    }
}
