/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_role",
    schema = "s_onthi"
)
public class OtRole implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long idRole;
    private String roleDescribe;
    private String roleKey;
    private String roleName;
    private Boolean active;
    private LocalDateTime createdDate;
    private String lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public OtRole() {}

    public OtRole(OtRole value) {
        this.idRole = value.idRole;
        this.roleDescribe = value.roleDescribe;
        this.roleKey = value.roleKey;
        this.roleName = value.roleName;
        this.active = value.active;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public OtRole(
        Long idRole,
        String roleDescribe,
        String roleKey,
        String roleName,
        Boolean active,
        LocalDateTime createdDate,
        String lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.idRole = idRole;
        this.roleDescribe = roleDescribe;
        this.roleKey = roleKey;
        this.roleName = roleName;
        this.active = active;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>s_onthi.ot_role.ID_ROLE</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_ROLE", nullable = false)
    public Long getIdRole() {
        return this.idRole;
    }

    /**
     * Setter for <code>s_onthi.ot_role.ID_ROLE</code>.
     */
    public void setIdRole(Long idRole) {
        this.idRole = idRole;
    }

    /**
     * Getter for <code>s_onthi.ot_role.ROLE_DESCRIBE</code>.
     */
    @Column(name = "ROLE_DESCRIBE", length = 255)
    public String getRoleDescribe() {
        return this.roleDescribe;
    }

    /**
     * Setter for <code>s_onthi.ot_role.ROLE_DESCRIBE</code>.
     */
    public void setRoleDescribe(String roleDescribe) {
        this.roleDescribe = roleDescribe;
    }

    /**
     * Getter for <code>s_onthi.ot_role.ROLE_KEY</code>.
     */
    @Column(name = "ROLE_KEY", nullable = false, length = 20)
    public String getRoleKey() {
        return this.roleKey;
    }

    /**
     * Setter for <code>s_onthi.ot_role.ROLE_KEY</code>.
     */
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey;
    }

    /**
     * Getter for <code>s_onthi.ot_role.ROLE_NAME</code>.
     */
    @Column(name = "ROLE_NAME", nullable = false, length = 50)
    public String getRoleName() {
        return this.roleName;
    }

    /**
     * Setter for <code>s_onthi.ot_role.ROLE_NAME</code>.
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * Getter for <code>s_onthi.ot_role.ACTIVE</code>.
     */
    @Column(name = "ACTIVE", nullable = false)
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>s_onthi.ot_role.ACTIVE</code>.
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * Getter for <code>s_onthi.ot_role.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>s_onthi.ot_role.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>s_onthi.ot_role.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>s_onthi.ot_role.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>s_onthi.ot_role.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>s_onthi.ot_role.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OtRole other = (OtRole) obj;
        if (this.idRole == null) {
            if (other.idRole != null)
                return false;
        }
        else if (!this.idRole.equals(other.idRole))
            return false;
        if (this.roleDescribe == null) {
            if (other.roleDescribe != null)
                return false;
        }
        else if (!this.roleDescribe.equals(other.roleDescribe))
            return false;
        if (this.roleKey == null) {
            if (other.roleKey != null)
                return false;
        }
        else if (!this.roleKey.equals(other.roleKey))
            return false;
        if (this.roleName == null) {
            if (other.roleName != null)
                return false;
        }
        else if (!this.roleName.equals(other.roleName))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idRole == null) ? 0 : this.idRole.hashCode());
        result = prime * result + ((this.roleDescribe == null) ? 0 : this.roleDescribe.hashCode());
        result = prime * result + ((this.roleKey == null) ? 0 : this.roleKey.hashCode());
        result = prime * result + ((this.roleName == null) ? 0 : this.roleName.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtRole (");

        sb.append(idRole);
        sb.append(", ").append(roleDescribe);
        sb.append(", ").append(roleKey);
        sb.append(", ").append(roleName);
        sb.append(", ").append(active);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(lastModifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
