/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_school",
    schema = "s_onthi"
)
public class OtSchool implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long idSchool;
    private Long idProvince;
    private String schoolName;
    private Long typeSchool;
    private LocalDateTime createdDate;
    private String lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public OtSchool() {}

    public OtSchool(OtSchool value) {
        this.idSchool = value.idSchool;
        this.idProvince = value.idProvince;
        this.schoolName = value.schoolName;
        this.typeSchool = value.typeSchool;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public OtSchool(
        Long idSchool,
        Long idProvince,
        String schoolName,
        Long typeSchool,
        LocalDateTime createdDate,
        String lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.idSchool = idSchool;
        this.idProvince = idProvince;
        this.schoolName = schoolName;
        this.typeSchool = typeSchool;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>s_onthi.ot_school.ID_SCHOOL</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_SCHOOL", nullable = false)
    public Long getIdSchool() {
        return this.idSchool;
    }

    /**
     * Setter for <code>s_onthi.ot_school.ID_SCHOOL</code>.
     */
    public void setIdSchool(Long idSchool) {
        this.idSchool = idSchool;
    }

    /**
     * Getter for <code>s_onthi.ot_school.ID_PROVINCE</code>.
     */
    @Column(name = "ID_PROVINCE")
    public Long getIdProvince() {
        return this.idProvince;
    }

    /**
     * Setter for <code>s_onthi.ot_school.ID_PROVINCE</code>.
     */
    public void setIdProvince(Long idProvince) {
        this.idProvince = idProvince;
    }

    /**
     * Getter for <code>s_onthi.ot_school.SCHOOL_NAME</code>.
     */
    @Column(name = "SCHOOL_NAME", nullable = false, length = 50)
    public String getSchoolName() {
        return this.schoolName;
    }

    /**
     * Setter for <code>s_onthi.ot_school.SCHOOL_NAME</code>.
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * Getter for <code>s_onthi.ot_school.TYPE_SCHOOL</code>.
     */
    @Column(name = "TYPE_SCHOOL")
    public Long getTypeSchool() {
        return this.typeSchool;
    }

    /**
     * Setter for <code>s_onthi.ot_school.TYPE_SCHOOL</code>.
     */
    public void setTypeSchool(Long typeSchool) {
        this.typeSchool = typeSchool;
    }

    /**
     * Getter for <code>s_onthi.ot_school.CREATED_DATE</code>.
     */
    @Column(name = "CREATED_DATE", precision = 6)
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>s_onthi.ot_school.CREATED_DATE</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>s_onthi.ot_school.LAST_MODIFIED_BY</code>.
     */
    @Column(name = "LAST_MODIFIED_BY", length = 50)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>s_onthi.ot_school.LAST_MODIFIED_BY</code>.
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>s_onthi.ot_school.LAST_MODIFIED_DATE</code>.
     */
    @Column(name = "LAST_MODIFIED_DATE", precision = 6)
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>s_onthi.ot_school.LAST_MODIFIED_DATE</code>.
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OtSchool other = (OtSchool) obj;
        if (this.idSchool == null) {
            if (other.idSchool != null)
                return false;
        }
        else if (!this.idSchool.equals(other.idSchool))
            return false;
        if (this.idProvince == null) {
            if (other.idProvince != null)
                return false;
        }
        else if (!this.idProvince.equals(other.idProvince))
            return false;
        if (this.schoolName == null) {
            if (other.schoolName != null)
                return false;
        }
        else if (!this.schoolName.equals(other.schoolName))
            return false;
        if (this.typeSchool == null) {
            if (other.typeSchool != null)
                return false;
        }
        else if (!this.typeSchool.equals(other.typeSchool))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idSchool == null) ? 0 : this.idSchool.hashCode());
        result = prime * result + ((this.idProvince == null) ? 0 : this.idProvince.hashCode());
        result = prime * result + ((this.schoolName == null) ? 0 : this.schoolName.hashCode());
        result = prime * result + ((this.typeSchool == null) ? 0 : this.typeSchool.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtSchool (");

        sb.append(idSchool);
        sb.append(", ").append(idProvince);
        sb.append(", ").append(schoolName);
        sb.append(", ").append(typeSchool);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(lastModifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
