/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_user_course",
    schema = "s_onthi",
    indexes = {
        @Index(name = "ID_COURSE", columnList = "ID_COURSE ASC"),
        @Index(name = "ID_USER", columnList = "ID_USER ASC")
    }
)
public class OtUserCourse implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long idUserCourse;
    private Long idUser;
    private Long idCourse;
    private Long learningLesson;
    private String learnedLesson;
    private String timeSchedule;

    public OtUserCourse() {}

    public OtUserCourse(OtUserCourse value) {
        this.idUserCourse = value.idUserCourse;
        this.idUser = value.idUser;
        this.idCourse = value.idCourse;
        this.learningLesson = value.learningLesson;
        this.learnedLesson = value.learnedLesson;
        this.timeSchedule = value.timeSchedule;
    }

    public OtUserCourse(
        Long idUserCourse,
        Long idUser,
        Long idCourse,
        Long learningLesson,
        String learnedLesson,
        String timeSchedule
    ) {
        this.idUserCourse = idUserCourse;
        this.idUser = idUser;
        this.idCourse = idCourse;
        this.learningLesson = learningLesson;
        this.learnedLesson = learnedLesson;
        this.timeSchedule = timeSchedule;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_USER_COURSE</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_USER_COURSE", nullable = false)
    public Long getIdUserCourse() {
        return this.idUserCourse;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_USER_COURSE</code>.
     */
    public void setIdUserCourse(Long idUserCourse) {
        this.idUserCourse = idUserCourse;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_USER</code>.
     */
    @Column(name = "ID_USER", nullable = false)
    public Long getIdUser() {
        return this.idUser;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_USER</code>.
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_COURSE</code>.
     */
    @Column(name = "ID_COURSE", nullable = false)
    public Long getIdCourse() {
        return this.idCourse;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_COURSE</code>.
     */
    public void setIdCourse(Long idCourse) {
        this.idCourse = idCourse;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.LEARNING_LESSON</code>.
     */
    @Column(name = "LEARNING_LESSON")
    public Long getLearningLesson() {
        return this.learningLesson;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.LEARNING_LESSON</code>.
     */
    public void setLearningLesson(Long learningLesson) {
        this.learningLesson = learningLesson;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.LEARNED_LESSON</code>.
     */
    @Column(name = "LEARNED_LESSON", length = 5000)
    public String getLearnedLesson() {
        return this.learnedLesson;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.LEARNED_LESSON</code>.
     */
    public void setLearnedLesson(String learnedLesson) {
        this.learnedLesson = learnedLesson;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.TIME_SCHEDULE</code>.
     */
    @Column(name = "TIME_SCHEDULE", length = 50)
    public String getTimeSchedule() {
        return this.timeSchedule;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.TIME_SCHEDULE</code>.
     */
    public void setTimeSchedule(String timeSchedule) {
        this.timeSchedule = timeSchedule;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OtUserCourse other = (OtUserCourse) obj;
        if (this.idUserCourse == null) {
            if (other.idUserCourse != null)
                return false;
        }
        else if (!this.idUserCourse.equals(other.idUserCourse))
            return false;
        if (this.idUser == null) {
            if (other.idUser != null)
                return false;
        }
        else if (!this.idUser.equals(other.idUser))
            return false;
        if (this.idCourse == null) {
            if (other.idCourse != null)
                return false;
        }
        else if (!this.idCourse.equals(other.idCourse))
            return false;
        if (this.learningLesson == null) {
            if (other.learningLesson != null)
                return false;
        }
        else if (!this.learningLesson.equals(other.learningLesson))
            return false;
        if (this.learnedLesson == null) {
            if (other.learnedLesson != null)
                return false;
        }
        else if (!this.learnedLesson.equals(other.learnedLesson))
            return false;
        if (this.timeSchedule == null) {
            if (other.timeSchedule != null)
                return false;
        }
        else if (!this.timeSchedule.equals(other.timeSchedule))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idUserCourse == null) ? 0 : this.idUserCourse.hashCode());
        result = prime * result + ((this.idUser == null) ? 0 : this.idUser.hashCode());
        result = prime * result + ((this.idCourse == null) ? 0 : this.idCourse.hashCode());
        result = prime * result + ((this.learningLesson == null) ? 0 : this.learningLesson.hashCode());
        result = prime * result + ((this.learnedLesson == null) ? 0 : this.learnedLesson.hashCode());
        result = prime * result + ((this.timeSchedule == null) ? 0 : this.timeSchedule.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtUserCourse (");

        sb.append(idUserCourse);
        sb.append(", ").append(idUser);
        sb.append(", ").append(idCourse);
        sb.append(", ").append(learningLesson);
        sb.append(", ").append(learnedLesson);
        sb.append(", ").append(timeSchedule);

        sb.append(")");
        return sb.toString();
    }
}
