/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_user_role",
    schema = "s_onthi",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_ot_user_role_ID_USER", columnNames = { "ID_USER" }),
        @UniqueConstraint(name = "KEY_ot_user_role_ID_ROLE", columnNames = { "ID_ROLE" })
    }
)
public class OtUserRole implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long idUser;
    private Long idRole;

    public OtUserRole() {}

    public OtUserRole(OtUserRole value) {
        this.id = value.id;
        this.idUser = value.idUser;
        this.idRole = value.idRole;
    }

    public OtUserRole(
        Long id,
        Long idUser,
        Long idRole
    ) {
        this.id = id;
        this.idUser = idUser;
        this.idRole = idRole;
    }

    /**
     * Getter for <code>s_onthi.ot_user_role.ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>s_onthi.ot_user_role.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>s_onthi.ot_user_role.ID_USER</code>.
     */
    @Column(name = "ID_USER", nullable = false)
    public Long getIdUser() {
        return this.idUser;
    }

    /**
     * Setter for <code>s_onthi.ot_user_role.ID_USER</code>.
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * Getter for <code>s_onthi.ot_user_role.ID_ROLE</code>.
     */
    @Column(name = "ID_ROLE", nullable = false)
    public Long getIdRole() {
        return this.idRole;
    }

    /**
     * Setter for <code>s_onthi.ot_user_role.ID_ROLE</code>.
     */
    public void setIdRole(Long idRole) {
        this.idRole = idRole;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OtUserRole other = (OtUserRole) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.idUser == null) {
            if (other.idUser != null)
                return false;
        }
        else if (!this.idUser.equals(other.idUser))
            return false;
        if (this.idRole == null) {
            if (other.idRole != null)
                return false;
        }
        else if (!this.idRole.equals(other.idRole))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.idUser == null) ? 0 : this.idUser.hashCode());
        result = prime * result + ((this.idRole == null) ? 0 : this.idRole.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtUserRole (");

        sb.append(id);
        sb.append(", ").append(idUser);
        sb.append(", ").append(idRole);

        sb.append(")");
        return sb.toString();
    }
}
