/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ot_user_course",
    schema = "s_onthi",
    indexes = {
        @Index(name = "ID_COURSE", columnList = "ID_COURSE ASC"),
        @Index(name = "ID_USER", columnList = "ID_USER ASC")
    }
)
public class OtUserCourse implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long idUserCourse;
    private Long idUser;
    private Long idCourse;

    public OtUserCourse() {}

    public OtUserCourse(OtUserCourse value) {
        this.idUserCourse = value.idUserCourse;
        this.idUser = value.idUser;
        this.idCourse = value.idCourse;
    }

    public OtUserCourse(
        Long idUserCourse,
        Long idUser,
        Long idCourse
    ) {
        this.idUserCourse = idUserCourse;
        this.idUser = idUser;
        this.idCourse = idCourse;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_USER_COURSE</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_USER_COURSE", nullable = false)
    public Long getIdUserCourse() {
        return this.idUserCourse;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_USER_COURSE</code>.
     */
    public void setIdUserCourse(Long idUserCourse) {
        this.idUserCourse = idUserCourse;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_USER</code>.
     */
    @Column(name = "ID_USER", nullable = false)
    public Long getIdUser() {
        return this.idUser;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_USER</code>.
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * Getter for <code>s_onthi.ot_user_course.ID_COURSE</code>.
     */
    @Column(name = "ID_COURSE", nullable = false)
    public Long getIdCourse() {
        return this.idCourse;
    }

    /**
     * Setter for <code>s_onthi.ot_user_course.ID_COURSE</code>.
     */
    public void setIdCourse(Long idCourse) {
        this.idCourse = idCourse;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OtUserCourse other = (OtUserCourse) obj;
        if (this.idUserCourse == null) {
            if (other.idUserCourse != null)
                return false;
        }
        else if (!this.idUserCourse.equals(other.idUserCourse))
            return false;
        if (this.idUser == null) {
            if (other.idUser != null)
                return false;
        }
        else if (!this.idUser.equals(other.idUser))
            return false;
        if (this.idCourse == null) {
            if (other.idCourse != null)
                return false;
        }
        else if (!this.idCourse.equals(other.idCourse))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idUserCourse == null) ? 0 : this.idUserCourse.hashCode());
        result = prime * result + ((this.idUser == null) ? 0 : this.idUser.hashCode());
        result = prime * result + ((this.idCourse == null) ? 0 : this.idCourse.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OtUserCourse (");

        sb.append(idUserCourse);
        sb.append(", ").append(idUser);
        sb.append(", ").append(idCourse);

        sb.append(")");
        return sb.toString();
    }
}
