/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities;


import cfm.onthi.entities.tables.OtCourse;
import cfm.onthi.entities.tables.OtDocument;
import cfm.onthi.entities.tables.OtGroup;
import cfm.onthi.entities.tables.OtLesson;
import cfm.onthi.entities.tables.OtMenu;
import cfm.onthi.entities.tables.OtMessage;
import cfm.onthi.entities.tables.OtMessageRecipient;
import cfm.onthi.entities.tables.OtNote;
import cfm.onthi.entities.tables.OtProvince;
import cfm.onthi.entities.tables.OtQuiz;
import cfm.onthi.entities.tables.OtReview;
import cfm.onthi.entities.tables.OtRole;
import cfm.onthi.entities.tables.OtRoleMenu;
import cfm.onthi.entities.tables.OtSchool;
import cfm.onthi.entities.tables.OtUser;
import cfm.onthi.entities.tables.OtUserCourse;
import cfm.onthi.entities.tables.OtUserGroup;
import cfm.onthi.entities.tables.OtUserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SOnthi extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s_onthi</code>
     */
    public static final SOnthi S_ONTHI = new SOnthi();

    /**
     * The table <code>s_onthi.ot_course</code>.
     */
    public final OtCourse OT_COURSE = OtCourse.OT_COURSE;

    /**
     * The table <code>s_onthi.ot_document</code>.
     */
    public final OtDocument OT_DOCUMENT = OtDocument.OT_DOCUMENT;

    /**
     * The table <code>s_onthi.ot_group</code>.
     */
    public final OtGroup OT_GROUP = OtGroup.OT_GROUP;

    /**
     * The table <code>s_onthi.ot_lesson</code>.
     */
    public final OtLesson OT_LESSON = OtLesson.OT_LESSON;

    /**
     * The table <code>s_onthi.ot_menu</code>.
     */
    public final OtMenu OT_MENU = OtMenu.OT_MENU;

    /**
     * The table <code>s_onthi.ot_message</code>.
     */
    public final OtMessage OT_MESSAGE = OtMessage.OT_MESSAGE;

    /**
     * The table <code>s_onthi.ot_message_recipient</code>.
     */
    public final OtMessageRecipient OT_MESSAGE_RECIPIENT = OtMessageRecipient.OT_MESSAGE_RECIPIENT;

    /**
     * The table <code>s_onthi.ot_note</code>.
     */
    public final OtNote OT_NOTE = OtNote.OT_NOTE;

    /**
     * The table <code>s_onthi.ot_province</code>.
     */
    public final OtProvince OT_PROVINCE = OtProvince.OT_PROVINCE;

    /**
     * The table <code>s_onthi.ot_quiz</code>.
     */
    public final OtQuiz OT_QUIZ = OtQuiz.OT_QUIZ;

    /**
     * The table <code>s_onthi.ot_review</code>.
     */
    public final OtReview OT_REVIEW = OtReview.OT_REVIEW;

    /**
     * The table <code>s_onthi.ot_role</code>.
     */
    public final OtRole OT_ROLE = OtRole.OT_ROLE;

    /**
     * The table <code>s_onthi.ot_role_menu</code>.
     */
    public final OtRoleMenu OT_ROLE_MENU = OtRoleMenu.OT_ROLE_MENU;

    /**
     * The table <code>s_onthi.ot_school</code>.
     */
    public final OtSchool OT_SCHOOL = OtSchool.OT_SCHOOL;

    /**
     * The table <code>s_onthi.ot_user</code>.
     */
    public final OtUser OT_USER = OtUser.OT_USER;

    /**
     * The table <code>s_onthi.ot_user_course</code>.
     */
    public final OtUserCourse OT_USER_COURSE = OtUserCourse.OT_USER_COURSE;

    /**
     * The table <code>s_onthi.ot_user_group</code>.
     */
    public final OtUserGroup OT_USER_GROUP = OtUserGroup.OT_USER_GROUP;

    /**
     * The table <code>s_onthi.ot_user_role</code>.
     */
    public final OtUserRole OT_USER_ROLE = OtUserRole.OT_USER_ROLE;

    /**
     * No further instances allowed
     */
    private SOnthi() {
        super("s_onthi", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            OtCourse.OT_COURSE,
            OtDocument.OT_DOCUMENT,
            OtGroup.OT_GROUP,
            OtLesson.OT_LESSON,
            OtMenu.OT_MENU,
            OtMessage.OT_MESSAGE,
            OtMessageRecipient.OT_MESSAGE_RECIPIENT,
            OtNote.OT_NOTE,
            OtProvince.OT_PROVINCE,
            OtQuiz.OT_QUIZ,
            OtReview.OT_REVIEW,
            OtRole.OT_ROLE,
            OtRoleMenu.OT_ROLE_MENU,
            OtSchool.OT_SCHOOL,
            OtUser.OT_USER,
            OtUserCourse.OT_USER_COURSE,
            OtUserGroup.OT_USER_GROUP,
            OtUserRole.OT_USER_ROLE
        );
    }
}
