/*
 * This file is generated by jOOQ.
 */
package cfm.onthi.entities;


import cfm.onthi.entities.tables.OtCourse;
import cfm.onthi.entities.tables.OtDocument;
import cfm.onthi.entities.tables.OtExercise;
import cfm.onthi.entities.tables.OtGroup;
import cfm.onthi.entities.tables.OtLesson;
import cfm.onthi.entities.tables.OtMenu;
import cfm.onthi.entities.tables.OtMessage;
import cfm.onthi.entities.tables.OtMessageRecipient;
import cfm.onthi.entities.tables.OtNote;
import cfm.onthi.entities.tables.OtProvince;
import cfm.onthi.entities.tables.OtQuiz;
import cfm.onthi.entities.tables.OtQuizUser;
import cfm.onthi.entities.tables.OtReview;
import cfm.onthi.entities.tables.OtReviewUser;
import cfm.onthi.entities.tables.OtRole;
import cfm.onthi.entities.tables.OtRoleMenu;
import cfm.onthi.entities.tables.OtSchool;
import cfm.onthi.entities.tables.OtUser;
import cfm.onthi.entities.tables.OtUserCourse;
import cfm.onthi.entities.tables.OtUserGroup;
import cfm.onthi.entities.tables.OtUserRole;


/**
 * Convenience access to all tables in s_onthi.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s_onthi.ot_course</code>.
     */
    public static final OtCourse OT_COURSE = OtCourse.OT_COURSE;

    /**
     * The table <code>s_onthi.ot_document</code>.
     */
    public static final OtDocument OT_DOCUMENT = OtDocument.OT_DOCUMENT;

    /**
     * The table <code>s_onthi.ot_exercise</code>.
     */
    public static final OtExercise OT_EXERCISE = OtExercise.OT_EXERCISE;

    /**
     * The table <code>s_onthi.ot_group</code>.
     */
    public static final OtGroup OT_GROUP = OtGroup.OT_GROUP;

    /**
     * The table <code>s_onthi.ot_lesson</code>.
     */
    public static final OtLesson OT_LESSON = OtLesson.OT_LESSON;

    /**
     * The table <code>s_onthi.ot_menu</code>.
     */
    public static final OtMenu OT_MENU = OtMenu.OT_MENU;

    /**
     * The table <code>s_onthi.ot_message</code>.
     */
    public static final OtMessage OT_MESSAGE = OtMessage.OT_MESSAGE;

    /**
     * The table <code>s_onthi.ot_message_recipient</code>.
     */
    public static final OtMessageRecipient OT_MESSAGE_RECIPIENT = OtMessageRecipient.OT_MESSAGE_RECIPIENT;

    /**
     * The table <code>s_onthi.ot_note</code>.
     */
    public static final OtNote OT_NOTE = OtNote.OT_NOTE;

    /**
     * The table <code>s_onthi.ot_province</code>.
     */
    public static final OtProvince OT_PROVINCE = OtProvince.OT_PROVINCE;

    /**
     * The table <code>s_onthi.ot_quiz</code>.
     */
    public static final OtQuiz OT_QUIZ = OtQuiz.OT_QUIZ;

    /**
     * The table <code>s_onthi.ot_quiz_user</code>.
     */
    public static final OtQuizUser OT_QUIZ_USER = OtQuizUser.OT_QUIZ_USER;

    /**
     * The table <code>s_onthi.ot_review</code>.
     */
    public static final OtReview OT_REVIEW = OtReview.OT_REVIEW;

    /**
     * The table <code>s_onthi.ot_review_user</code>.
     */
    public static final OtReviewUser OT_REVIEW_USER = OtReviewUser.OT_REVIEW_USER;

    /**
     * The table <code>s_onthi.ot_role</code>.
     */
    public static final OtRole OT_ROLE = OtRole.OT_ROLE;

    /**
     * The table <code>s_onthi.ot_role_menu</code>.
     */
    public static final OtRoleMenu OT_ROLE_MENU = OtRoleMenu.OT_ROLE_MENU;

    /**
     * The table <code>s_onthi.ot_school</code>.
     */
    public static final OtSchool OT_SCHOOL = OtSchool.OT_SCHOOL;

    /**
     * The table <code>s_onthi.ot_user</code>.
     */
    public static final OtUser OT_USER = OtUser.OT_USER;

    /**
     * The table <code>s_onthi.ot_user_course</code>.
     */
    public static final OtUserCourse OT_USER_COURSE = OtUserCourse.OT_USER_COURSE;

    /**
     * The table <code>s_onthi.ot_user_group</code>.
     */
    public static final OtUserGroup OT_USER_GROUP = OtUserGroup.OT_USER_GROUP;

    /**
     * The table <code>s_onthi.ot_user_role</code>.
     */
    public static final OtUserRole OT_USER_ROLE = OtUserRole.OT_USER_ROLE;
}
